package com.jdbc.starter;

import com.jdbc.starter.util.ConnectionManager;

import java.sql.*;
import java.util.Iterator;

public class JdbcRunner {
    public static void main(String[] args) throws SQLException {
        Class<Driver> driverClass = Driver.class;
        String sql = """
                CREATE TABLE IF NOT EXISTS info
                (
                    id BIGINT AUTO_INCREMENT PRIMARY KEY,
                    name VARCHAR(128) NOT NULL
                );
                """;
        String sql1 = """
                DROP TABLE IF EXISTS info;
                """;
        String sql2 = """
                INSERT INTO info (name)
                VALUES
                ('Test autogenerated');
                """;
        String sql3 = """
                DELETE FROM info;
                """;
        String sql4 = """
                UPDATE info
                SET name = 'Very test'
                WHERE id = 7;
                """;
        String sql5 = """
                SELECT * FROM ticket;
                """;
        try (Connection connection = ConnectionManager.open();
             Statement statement = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE)) {


            System.out.println(connection.getSchema());
            System.out.println(connection.getTransactionIsolation()); // Transaction status

//            boolean executeResult = statement.execute(sql); // DDL operations
//            System.out.println(executeResult);
//            System.out.println(statement.getUpdateCount());
//            int result = statement.executeUpdate(sql4); // DML operations
//            System.out.println(result);
//            ResultSet resultSet = statement.executeQuery(sql5); // only operation SELECT
//            while(resultSet.next()){
//                System.out.println(resultSet.getInt("id"));
//                System.out.println(resultSet.getString("passenger_no"));
//                System.out.println(resultSet.getString("passenger_name"));
//                System.out.println(resultSet.getBigDecimal("cost"));
//                System.out.println("--------------------");
//            }
            int result = statement.executeUpdate(sql2, Statement.RETURN_GENERATED_KEYS); // return id after insert into
            ResultSet generatedKeys = statement.getGeneratedKeys();
            if (generatedKeys.next()){
                int id = generatedKeys.getInt(1);
                System.out.println(id);
            }
        }
    }
}
